---
# tasks file for ubnt


- name: install Java openjdk
  yum:
    name: java-1.8.0-openjdk-devel
    lock_timeout: 120
  become: yes

- name: adding the MongoDB repo
  yum_repository:
    name: mongodb-org-4.0
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.0/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.0.asc
  become: yes


- name: install mongo-server
  yum: 
    name: mongodb-org
    state: latest
    lock_timeout: 120
  become: yes

- name: start mongo-server
  service:
    name: mongod
    state: started
    enabled: yes
  become: yes


- name: create ubnt user
  user:
    name: ubnt
    create_home: no
  become: yes


- name: download unifi package
  unarchive:
    src: 'http://dl.ubnt.com/unifi/{{ _ubnt_version_ }}/UniFi.unix.zip'
    dest: /opt/
    owner: ubnt
    group: ubnt
    keep_newer: yes
    remote_src: yes
  become: yes

- name: copy unifi.service
  copy:
    src: ../files/unifi.service
    dest: /etc/systemd/system/
  become: yes

- name: start unifi service
  service: 
    name: unifi
    state: started
    enabled: yes
  become: yes