---
# tasks file for update

- name: stop unifi service
  service:
    name: unifi
    state: stopped
  become: yes

- name: stop mongo service
  service:
    name: mongod
    state: stopped
  become: yes

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    lock_timeout: 120
  become: yes

- name: copy UniFi folder
  copy:
    src: /opt/UniFi
    dest: /opt/UniFi_old
    remote_src: yes
  become: yes

- name: delete old UniFi folder
  file:
    path: /opt/UniFi
    state: absent
  become: yes

- name: download new unifi package
  unarchive:
    src: 'https://dl.ui.com/unifi/{{ _ubnt_version_ }}/UniFi.unix.zip'
    dest: /opt/
    owner: ubnt
    group: ubnt
    remote_src: yes
  become: yes

- name: copy data & configuration files
  copy:
    src: /opt/UniFi_old/UniFi/data
    dest: /opt/UniFi/
    owner: ubnt
    group: ubnt
    remote_src: yes
  become: yes

- name: start mongo service
  service:
    name: mongod
    state: started
    enabled: yes
  become: yes

- name: start unifi service
  service:
    name: unifi
    state: started
    enabled: yes
  become: yes
