---
AWSTemplateFormatVersion: "2010-09-09"

Description: Memecache Cluster

Parameters:
  Subnets:
    Description: Subnets to attach to the load balancer
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Security group to attach to the load balancer
    Type: String

  CacheNodeCapacityType:
    Description: Instance Type
    Type: String
    Default: cache.t3.micro
    AllowedValues:
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium

  CacheNodeNumber:
    Description: number of cache nodes
    Type: Number
    Default: 2

Resources:
  CacheClusterSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub "${AWS::StackName}-cache-subnet"
      Description: Cache Subnet for Wordpress
      SubnetIds:
        - !Select [0, !Ref Subnets]
        - !Select [1, !Ref Subnets]

  MemcacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref CacheNodeCapacityType
      CacheSubnetGroupName: !Ref CacheClusterSubnetGroup
      Engine: memcached
      NumCacheNodes: !Ref CacheNodeNumber
      VpcSecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-cache-cluster"
        - Key: stack
          Value: !Ref AWS::StackName

Outputs:
  MemcacheEndpoint:
    Description: "The DNS address of the primary read-write cache node."
    Value: !GetAtt MemcacheCluster.ConfigurationEndpoint.Address

  RedisPort:
    Description: "Port for Redis"
    Value: !GetAtt MemcacheCluster.ConfigurationEndpoint.Port
