---
AWSTemplateFormatVersion: "2010-09-09"
Description: Task and Service Definition

Parameters:
  ECSCluster:
    Type: String
  DesiredCount:
    Type: Number
    Default: 2
  ContainerCpu:
    Type: Number
    Default: 1024
  ContainerMemory:
    Type: Number
    Default: 2048
  ClusterRoleArn:
    Type: String
  TargetGroupArn:
    Type: String
  EFSId:
    Type: String
    Description: The Amazon EFS file system ID to use
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroup:
    Description: Security group
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  UnifiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: !Ref ClusterRoleArn
      TaskRoleArn: !Ref ClusterRoleArn
      ContainerDefinitions:
        - Name: "unifi-controller"
          Image: linuxserver/unifi-controller
          Essential: true
          MountPoints:
            - ContainerPath: /config
              ReadOnly: false
              SourceVolume: unifi-content
          PortMappings:
            - ContainerPort: 3478
              HostPort: 3478
              Protocol: udp
            - ContainerPort: 10001
              HostPort: 10001
              Protocol: udp
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
            - ContainerPort: 8443
              HostPort: 8443
              Protocol: tcp
            - ContainerPort: 8880
              HostPort: 8880
              Protocol: tcp
            - ContainerPort: 6789
              HostPort: 6789
              Protocol: tcp
            - ContainerPort: 5514
              HostPort: 5514
              Protocol: tcp
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-region: !Sub ${AWS::Region}
              awslogs-group: !Sub "/ecs/${ECSCluster}"
              awslogs-stream-prefix: "unifi-controller"
          Environment:
            - Name: PUID
              Value: "1000"
            - Name: PGID
              Value: "1000"
      Volumes:
        - EFSVolumeConfiguration:
            FilesystemId: !Ref EFSId
            RootDirectory: /
          Name: unifi-content

  UnifiControllerServiceDefinition:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: !Ref "DesiredCount"
      TaskDefinition: !Ref "UnifiTaskDefinition"
      PlatformVersion: "1.4.0"
      LoadBalancers:
        - ContainerName: "unifi-controller"
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SecurityGroup
          Subnets:
            - !Select [0, !Ref Subnets]
            - !Select [1, !Ref Subnets]

Outputs:
  UnifiControllerServiceName:
    Description: UniFi Controller Service name
    Value: !Ref UnifiControllerServiceDefinition
