---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  IAM Roles policies

Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
                - "ecs.amazonaws.com"
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AWSCodeCommitReadOnly

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2InstanceRole

  ECSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs.amazonaws.com"
                - "ec2.amazonaws.com"
                - "ecs-tasks.amazonaws.com"
                - "application-autoscaling.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-IAM-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecs:*"
                  - "ecs-tasks:*"
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "ecr:*"
                  - "cloudwatch:*"
                  - "s3:*"
                  - "rds:*"
                  - "sqs:*"
                  - "sns:*"
                  - "logs:*"
                  - "ssm:*"
                Resource: "*"

Outputs:
  EC2InstanceProfile:
    Description: "Instance profile for EC2"
    Value: !Ref EC2InstanceProfile

  EC2InstanceRole:
    Description: "EC2 Instance Role"
    Value: !GetAtt EC2InstanceRole.Arn

  ECSClusterRole:
    Description: "ECS Cluster Role"
    Value: !GetAtt ECSClusterRole.Arn
